### ISSUE TITLE
[3pts]Data and database(NoSQL) definition

### ISSUE THREAD

**Issue by EoWanjala** [EoWanjala/My_Cloud_Resume#1]
# Task 1; Define structure for NoSQL database
- [ ] Identify and choose the relevant database
- [ ] Define the structure of your resume data
- [ ] Implement/Populate resume data on the database
