### ISSUE TITLE
[3pts] Creating a Lambda function

### ISSUE THREAD

**Issue by EoWanjala** [EoWanjala/My_Cloud_Resume#2]
# Task 2; Create a serverless function
- [ ] Create a lmbada function.
- [ ] Specify code to fetch data from the database and run(display) it upon trigger.
- [ ] Contents displayed should be in json
